### ISSUE TITLE
blueprint mod support

### ISSUE THREAD

**Issue by 143mailliw** [StoneLineDevTeam/UMod#25]
please

**Comment by Yuri6037** [comment]
Well if I add lua that's not for nothing, UMod is intended to be a replacement to GMod. Blueprint Mod support will make Lua useless and will also create problems.
As you know, UMod has many issues with UE4's integrated GC, Blueprint will require that most of UMod classes to be UObject, which will probably mess the whole game.

BP in UMod is intended only for the menus, that's all.
I know the UModPlayer is a BP just because I haven't found a better way to get the player init fully done in C++.

However C++ mod support is not excluded as it would not break anything in the game, at least not if you know how to code...

**Comment by Yuri6037** [comment]
Little Note : BP is not downloadable from Server, unlike Lua, and I can not dynamically load them as those are UAssets forcing dynamic load of this type of file would be against End User Lisence Agreement.

Also you might tell me, but Lua just doesn't work ! Well I know that, and if you look at LuaEngine version you'll see a big NULL meaning it's partialy running... It's not fully running (that's why you can not send any file to the client you can only do quite a few things server side). Please just wait more time. I told you I'm advancing UMod in the local repo probably fixed a lot of issues, and also fixed a lot of possible crashes. And if you look at the logs of my local repo you'll get a surpise concerning LuaEngine it will actualy correct print it's version meaning it's now running the way it should, it just lacks of a lot of C++ Lua API functions.

**Comment by Yuri6037** [comment]
There you go the new repo is uploaded, try using that version.

**Comment by Yuri6037** [comment]
Wait, what would you like BP to mod ? The MainMenu/Load Screen ? If so that is possible as this is separated from any gameplay/network stuff.
